version: 2.1

jobs:
  test_and_build:
    docker:
      - image: cimg/node:22.14.0
    steps:
      - checkout
      - run: npm ci
      - run: npm t

workflows:
  version: 2
  test_and_build:
    jobs:
      - test_and_build
